# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Coveralls

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-front:

    runs-on: ubuntu-latest
        
    defaults:
      run:
        working-directory: ./client

    env:
      COVERALLS_PARALLEL: true
      
    steps:
    - name: Cloning repo
      uses: actions/checkout@v3
    - name: Use Node.js 19.x
      uses: actions/setup-node@v3
      with:
        node-version: 19.x
        cache: 'npm'
    - name: Installing dependencies
      run: npm ci
    - name: Generating coverage information
      run: npm run coverage
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ${{ github.workspace }}/client/coverage/lcov.info
        flag-name: run-frontend
        parallel: true
  

  test-back:

    runs-on: ubuntu-latest

    defaults:
        run:
          working-directory: ./server
        
    env:
      MONGO_DB_URI_TEST: mongodb+srv://SyTW:sytw123@cluster0.vrub0al.mongodb.net/test-app?retryWrites=true&w=majority
      COVERALLS_PARALLEL: true

    steps:
    - name: Cloning repo
      uses: actions/checkout@v3
    - name: Use Node.js 19.x
      uses: actions/setup-node@v3
      with:
        node-version: 19.x
        cache: 'npm'
    - name: Installing dependencies
      run: npm install
    - name: Generating coverage information
      run: npm run coverage
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ${{ github.workspace }}/server/coverage/lcov.info
        flag-name: run-backend
        parallel: true
  

  finish:
    needs: [test-front, test-back]
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true