name: Coveralls

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  coveralls:

    runs-on: ubuntu-latest
        
    defaults:
      run:
        working-directory: ./client
      
    steps:
    - name: Cloning repo
      uses: actions/checkout@v3
    - name: Use Node.js 19.x
      uses: actions/setup-node@v3
      with:
        node-version: 19.x
        cache: 'npm'
    - name: Installing dependencies
      run: npm ci
    - name: Generating coverage information
      run: npm run coverage
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ${{ github.workspace }}/client/coverage/lcov.info
        base-path: ${{ github.workspace }}/client